export enum PageEnum {
  INIT = "INIT",
  SCREEN_LIST_INVOICE = "SCREEN_LIST_INVOICE",
  SCREEN_CREATE_INVOICE = "SCREEN_CREATE_INVOICE",
  SCREEN_CREATE_BOLETA = "SCREEN_CREATE_BOLETA",
  SCREEN_CREATE_NOTA_VENTA = "SCREEN_CREATE_NOTA_VENTA",
}
